//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiLocalizationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiLocalizationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Tool.Localization.GuiLocalizationString", typeof(GuiLocalizationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开源的自制谱工具集.
        /// </summary>
        public static string app_subtitle {
            get {
                return ResourceManager.GetString("app_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaedePhi.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回导入.
        /// </summary>
        public static string btn_back_to_import {
            get {
                return ResourceManager.GetString("btn_back_to_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回工具.
        /// </summary>
        public static string btn_back_to_tools {
            get {
                return ResourceManager.GetString("btn_back_to_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string btn_export {
            get {
                return ResourceManager.GetString("btn_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出谱面.
        /// </summary>
        public static string btn_export_chart {
            get {
                return ResourceManager.GetString("btn_export_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行工具.
        /// </summary>
        public static string btn_run_tool {
            get {
                return ResourceManager.GetString("btn_run_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出格式.
        /// </summary>
        public static string export_output_format {
            get {
                return ResourceManager.GetString("export_output_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式写入.
        /// </summary>
        public static string export_stream_writing {
            get {
                return ResourceManager.GetString("export_stream_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出谱面.
        /// </summary>
        public static string export_title {
            get {
                return ResourceManager.GetString("export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件:.
        /// </summary>
        public static string header_file {
            get {
                return ResourceManager.GetString("header_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式:.
        /// </summary>
        public static string header_format {
            get {
                return ResourceManager.GetString("header_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入谱面文件.
        /// </summary>
        public static string import_button {
            get {
                return ResourceManager.GetString("import_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式加载.
        /// </summary>
        public static string import_stream_loading {
            get {
                return ResourceManager.GetString("import_stream_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序启动中....
        /// </summary>
        public static string log_app_starting {
            get {
                return ResourceManager.GetString("log_app_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问文件选择器。.
        /// </summary>
        public static string log_cannot_access_picker {
            get {
                return ResourceManager.GetString("log_cannot_access_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面已加载，准备处理。.
        /// </summary>
        public static string log_chart_ready {
            get {
                return ResourceManager.GetString("log_chart_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出已取消。.
        /// </summary>
        public static string log_export_cancelled {
            get {
                return ResourceManager.GetString("log_export_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出完成。.
        /// </summary>
        public static string log_export_done {
            get {
                return ResourceManager.GetString("log_export_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败。.
        /// </summary>
        public static string log_export_failed {
            get {
                return ResourceManager.GetString("log_export_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出至: {0}，格式: {1}.
        /// </summary>
        public static string log_exporting_to {
            get {
                return ResourceManager.GetString("log_exporting_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择文件: {0}, 流式={1}.
        /// </summary>
        public static string log_file_selected {
            get {
                return ResourceManager.GetString("log_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载文件失败。.
        /// </summary>
        public static string log_load_failed {
            get {
                return ResourceManager.GetString("log_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导航至导入页面。.
        /// </summary>
        public static string log_navigate_import {
            get {
                return ResourceManager.GetString("log_navigate_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在运行工具: {0}.
        /// </summary>
        public static string log_running_tool {
            get {
                return ResourceManager.GetString("log_running_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序关闭，正在清除工作区。.
        /// </summary>
        public static string log_shutdown {
            get {
                return ResourceManager.GetString("log_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在转换为 KPC....
        /// </summary>
        public static string log_step_converting {
            get {
                return ResourceManager.GetString("log_step_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已检测到格式: {0}.
        /// </summary>
        public static string log_step_detected {
            get {
                return ResourceManager.GetString("log_step_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载文件....
        /// </summary>
        public static string log_step_loading {
            get {
                return ResourceManager.GetString("log_step_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已保存至工作区。.
        /// </summary>
        public static string log_step_saved {
            get {
                return ResourceManager.GetString("log_step_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具 &quot;{0}&quot; 已完成。您可以运行其它工具或导出。.
        /// </summary>
        public static string log_tool_completed {
            get {
                return ResourceManager.GetString("log_tool_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具执行失败。.
        /// </summary>
        public static string log_tool_failed {
            get {
                return ResourceManager.GetString("log_tool_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区已清除。.
        /// </summary>
        public static string log_workspace_cleared {
            get {
                return ResourceManager.GetString("log_workspace_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍细分数.
        /// </summary>
        public static string option_beat_subdivisions {
            get {
                return ResourceManager.GetString("option_beat_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道宽度.
        /// </summary>
        public static string option_channel_width {
            get {
                return ResourceManager.GetString("option_channel_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经典模式.
        /// </summary>
        public static string option_classic_mode {
            get {
                return ResourceManager.GetString("option_classic_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用压缩.
        /// </summary>
        public static string option_disable_compress {
            get {
                return ResourceManager.GetString("option_disable_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍像素.
        /// </summary>
        public static string option_pixels_per_beat {
            get {
                return ResourceManager.GetString("option_pixels_per_beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精度.
        /// </summary>
        public static string option_precision {
            get {
                return ResourceManager.GetString("option_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每事件采样数.
        /// </summary>
        public static string option_samples_per_event {
            get {
                return ResourceManager.GetString("option_samples_per_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差 (%).
        /// </summary>
        public static string option_tolerance {
            get {
                return ResourceManager.GetString("option_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string processing_error {
            get {
                return ResourceManager.GetString("processing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志文件:.
        /// </summary>
        public static string processing_log_file {
            get {
                return ResourceManager.GetString("processing_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作已完成。.
        /// </summary>
        public static string processing_success {
            get {
                return ResourceManager.GetString("processing_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理谱面.
        /// </summary>
        public static string processing_title {
            get {
                return ResourceManager.GetString("processing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问文件选择器。.
        /// </summary>
        public static string status_cannot_access_picker {
            get {
                return ResourceManager.GetString("status_cannot_access_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误: {0}。详见日志: {1}.
        /// </summary>
        public static string status_error_with_log {
            get {
                return ResourceManager.GetString("status_error_with_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出已取消。.
        /// </summary>
        public static string status_export_cancelled {
            get {
                return ResourceManager.GetString("status_export_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导出至: {0}.
        /// </summary>
        public static string status_exported_to {
            get {
                return ResourceManager.GetString("status_exported_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出....
        /// </summary>
        public static string status_exporting {
            get {
                return ResourceManager.GetString("status_exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已加载 {0} 条判定线。.
        /// </summary>
        public static string status_loaded_lines {
            get {
                return ResourceManager.GetString("status_loaded_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理....
        /// </summary>
        public static string status_processing {
            get {
                return ResourceManager.GetString("status_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具 &quot;{0}&quot; 已完成。您可以运行其它工具或导出。.
        /// </summary>
        public static string status_tool_completed {
            get {
                return ResourceManager.GetString("status_tool_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推断格式.
        /// </summary>
        public static string step_detecting {
            get {
                return ResourceManager.GetString("step_detecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换回原始格式.
        /// </summary>
        public static string step_from_kpc {
            get {
                return ResourceManager.GetString("step_from_kpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载文件.
        /// </summary>
        public static string step_loading {
            get {
                return ResourceManager.GetString("step_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用工具.
        /// </summary>
        public static string step_running_tool {
            get {
                return ResourceManager.GetString("step_running_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出到工作区.
        /// </summary>
        public static string step_saving {
            get {
                return ResourceManager.GetString("step_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换为中间格式.
        /// </summary>
        public static string step_to_kpc {
            get {
                return ResourceManager.GetString("step_to_kpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将事件按等长段切割.
        /// </summary>
        public static string tool_cut_desc {
            get {
                return ResourceManager.GetString("tool_cut_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件切割.
        /// </summary>
        public static string tool_cut_name {
            get {
                return ResourceManager.GetString("tool_cut_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将线性事件拟合为缓动曲线.
        /// </summary>
        public static string tool_fit_desc {
            get {
                return ResourceManager.GetString("tool_fit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件拟合.
        /// </summary>
        public static string tool_fit_name {
            get {
                return ResourceManager.GetString("tool_fit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将多个事件层合并为单层.
        /// </summary>
        public static string tool_layermerge_desc {
            get {
                return ResourceManager.GetString("tool_layermerge_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层级合并.
        /// </summary>
        public static string tool_layermerge_name {
            get {
                return ResourceManager.GetString("tool_layermerge_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具选项.
        /// </summary>
        public static string tool_options_title {
            get {
                return ResourceManager.GetString("tool_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将谱面事件层渲染为图片.
        /// </summary>
        public static string tool_render_desc {
            get {
                return ResourceManager.GetString("tool_render_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件渲染.
        /// </summary>
        public static string tool_render_name {
            get {
                return ResourceManager.GetString("tool_render_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工具.
        /// </summary>
        public static string tool_select_title {
            get {
                return ResourceManager.GetString("tool_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将子判定线从父线坐标系解绑为绝对坐标.
        /// </summary>
        public static string tool_unbind_desc {
            get {
                return ResourceManager.GetString("tool_unbind_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父子线解绑.
        /// </summary>
        public static string tool_unbind_name {
            get {
                return ResourceManager.GetString("tool_unbind_name", resourceCulture);
            }
        }
    }
}
